[build]
  base    = "client"        # This points to your 'client' folder where the frontend code is located
  publish = "client/build"  # This is the directory where your build files will be after the build step
  command = "npm run build" # The command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
